// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcQgCDCO5pnXcI58Rxm12vF29ONcuRPY',
    appId: '1:632187575819:web:80d4f5f7cd74ff6ff7f10e',
    messagingSenderId: '632187575819',
    projectId: 'rental-room-c34cb',
    authDomain: 'rental-room-c34cb.firebaseapp.com',
    storageBucket: 'rental-room-c34cb.appspot.com',
    measurementId: 'G-JSPX637D14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClf41P1ZfT7rcty9k7CCTCjOgQwpFv1fU',
    appId: '1:632187575819:android:a4e32c8971ee7f43f7f10e',
    messagingSenderId: '632187575819',
    projectId: 'rental-room-c34cb',
    storageBucket: 'rental-room-c34cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczmPww_eWxPbb9B_UjKHle-5lodsNlZw',
    appId: '1:632187575819:ios:2ab1327bde807a69f7f10e',
    messagingSenderId: '632187575819',
    projectId: 'rental-room-c34cb',
    storageBucket: 'rental-room-c34cb.appspot.com',
    iosClientId: '632187575819-4jqegta0k1ran740ilvjmbv9r0tekb2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalRoomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczmPww_eWxPbb9B_UjKHle-5lodsNlZw',
    appId: '1:632187575819:ios:2ab1327bde807a69f7f10e',
    messagingSenderId: '632187575819',
    projectId: 'rental-room-c34cb',
    storageBucket: 'rental-room-c34cb.appspot.com',
    iosClientId: '632187575819-4jqegta0k1ran740ilvjmbv9r0tekb2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalRoomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhcQgCDCO5pnXcI58Rxm12vF29ONcuRPY',
    appId: '1:632187575819:web:b9f32bdc7b4a0a56f7f10e',
    messagingSenderId: '632187575819',
    projectId: 'rental-room-c34cb',
    authDomain: 'rental-room-c34cb.firebaseapp.com',
    storageBucket: 'rental-room-c34cb.appspot.com',
    measurementId: 'G-2RNT9SLLPL',
  );

}